/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;
import java.util.List;
import java.io.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
/**
 *
 * @author titoosemobor
 */
public class Deposit extends javax.swing.JFrame {
    private User user;
    private List<User> users;

    private ButtonGroup group = new ButtonGroup();

    /**
     * Creates new form Deposit1
     */
    public Deposit(List<User> users) {
        this.users = users;
    }
    public Deposit(User user, List<User> users) {
        this.user = user;
        this.users = users;


        initComponents();
        balanceText.setText("$" + String.valueOf(user.getCheckingsBalance()));
        twentyButton.setActionCommand("20");
        fourtyButton.setActionCommand("40");
        eightyButton.setActionCommand("80");
        hundredButton.setActionCommand("100");
        twoHundredButton.setActionCommand("200");
        threeHundredButton.setActionCommand("300");
        group.add(twentyButton);
        group.add(fourtyButton);
        group.add(eightyButton);
        group.add(hundredButton);
        group.add(twoHundredButton);
        group.add(threeHundredButton);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        depositLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        withdrawFromText = new javax.swing.JLabel();
        accountComboBox = new javax.swing.JComboBox<>();
        optionMenuButton = new javax.swing.JButton();
        currentBalancePanel = new javax.swing.JPanel();
        balanceText = new javax.swing.JLabel();
        currentBalanceTitle = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        twentyButton = new javax.swing.JToggleButton();
        fourtyButton = new javax.swing.JToggleButton();
        eightyButton = new javax.swing.JToggleButton();
        hundredButton = new javax.swing.JToggleButton();
        twoHundredButton = new javax.swing.JToggleButton();
        threeHundredButton = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MetCash");
        setMaximumSize(new java.awt.Dimension(734, 394));
        setPreferredSize(new java.awt.Dimension(734, 394));
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setMaximumSize(new java.awt.Dimension(734, 394));

        depositLabel.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        depositLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        depositLabel.setText("DEPOSIT");

        withdrawFromText.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        withdrawFromText.setText("Deposit From:");

        accountComboBox.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        accountComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Checkings Account", "Savings Account" }));
        accountComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountComboBoxActionPerformed(evt);
            }
        });

        optionMenuButton.setFont(new java.awt.Font("SansSerif", 1, 19)); // NOI18N
        optionMenuButton.setText("< Option Menu");
        optionMenuButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        optionMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionMenuButtonActionPerformed(evt);
            }
        });

        currentBalancePanel.setBackground(new java.awt.Color(220, 220, 220));
        currentBalancePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        balanceText.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        balanceText.setForeground(new java.awt.Color(51, 51, 51));
        balanceText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout currentBalancePanelLayout = new javax.swing.GroupLayout(currentBalancePanel);
        currentBalancePanel.setLayout(currentBalancePanelLayout);
        currentBalancePanelLayout.setHorizontalGroup(
            currentBalancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentBalancePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(balanceText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        currentBalancePanelLayout.setVerticalGroup(
            currentBalancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentBalancePanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(balanceText, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        currentBalanceTitle.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        currentBalanceTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentBalanceTitle.setText("BALANCE:");
        currentBalanceTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        confirmButton.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        twentyButton.setBackground(new java.awt.Color(153, 153, 153));
        twentyButton.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        twentyButton.setText("< $20");

        fourtyButton.setBackground(new java.awt.Color(153, 153, 153));
        fourtyButton.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        fourtyButton.setText("< $40");

        eightyButton.setBackground(new java.awt.Color(153, 153, 153));
        eightyButton.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        eightyButton.setText("< $80");

        hundredButton.setBackground(new java.awt.Color(153, 153, 153));
        hundredButton.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        hundredButton.setText("< $100");

        twoHundredButton.setBackground(new java.awt.Color(153, 153, 153));
        twoHundredButton.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        twoHundredButton.setText("< $200");

        threeHundredButton.setBackground(new java.awt.Color(153, 153, 153));
        threeHundredButton.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        threeHundredButton.setText("< $300");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fourtyButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                .addComponent(eightyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(twentyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(optionMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(currentBalancePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(currentBalanceTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(hundredButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                    .addComponent(twoHundredButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(threeHundredButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(withdrawFromText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accountComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(withdrawFromText)
                    .addComponent(accountComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(twentyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hundredButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fourtyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(twoHundredButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(threeHundredButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eightyButton)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(currentBalanceTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(currentBalancePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(optionMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/titoosemobor/TMU-ComputerSci/JAVA/ATMProject/assets/rsz_4rsz_1rsz_metcash-high-resolution-logo-black-on-transparent-background.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(175, 175, 175)
                        .addComponent(depositLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(depositLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void accountComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountComboBoxActionPerformed
        // TODO add your handling code here:
        String selectedItem = (String) accountComboBox.getSelectedItem();
        if (selectedItem.equals("Checkings Account")) {
            balanceText.setText("$" + String.valueOf(user.getCheckingsBalance()));
        }
        else {
            balanceText.setText("$" + String.valueOf(user.getSavingsBalance()));
        }
    }//GEN-LAST:event_accountComboBoxActionPerformed

    private void optionMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionMenuButtonActionPerformed
        // TODO add your handling code here:
        TransactionMenu login = new TransactionMenu(user, users);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_optionMenuButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        ButtonModel selected = group.getSelection();
        String selectedItem = null;
        String value = null;
        if (selected == null) {
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else {
            value = selected.getActionCommand();
            selectedItem = (String) accountComboBox.getSelectedItem();
            assert selectedItem != null;
            if (selectedItem.equals("Checkings Account")) {
                user.setCheckingsBalance(addToCheckings(user, value));
                addToTransactionHistoryCheckings("$" +value);
                balanceText.setText("$" + String.valueOf(user.getCheckingsBalance()));
            } else {
                user.setSavingsBalance(addToSavings(user, value));
                addToTransactionHistorySavings("$" +value);
                balanceText.setText("$" + String.valueOf(user.getSavingsBalance()));
            }
        }
    }//GEN-LAST:event_confirmButtonActionPerformed

    public static Integer addToCheckings(User user, String value) {
        Integer balance = user.getCheckingsBalance();
        switch (value) {
            case "20" -> balance += 20;
            case "40" -> balance += 40;
            case "80" -> balance += 80;
            case "100" -> balance += 100;
            case "200" -> balance += 200;
            case "300" -> balance += 300;
        }
        return balance;
    }

    public static Integer addToSavings(User user, String value) {
        Integer balance = user.getSavingsBalance();
        switch (value) {
            case "20" -> balance += 20;
            case "40" -> balance += 40;
            case "80" -> balance += 80;
            case "100" -> balance += 100;
            case "200" -> balance += 200;
            case "300" -> balance += 300;
        }
        return balance;
    }
    public void addToTransactionHistoryCheckings(String value){
        // Get the current date and time
        LocalDateTime now = LocalDateTime.now();

        // Format the date and time as a string
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        String formattedDateTime = now.format(formatter);

        try {
            // Open the file in append mode
            FileWriter fw = new FileWriter(user.getTransactionPaper(), true);
            BufferedWriter bw = new BufferedWriter(fw);

            // Append some data to the file
            bw.write("Deposited/"+value+"/Checkings/"+formattedDateTime+"\n");

            // Close the writers
            bw.close();
            fw.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    public void addToTransactionHistorySavings(String value){
        // Get the current date and time
        LocalDateTime now = LocalDateTime.now();

        // Format the date and time as a string
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        String formattedDateTime = now.format(formatter);

        try {
            // Open the file in append mode
            FileWriter fw = new FileWriter(user.getTransactionPaper(), true);
            BufferedWriter bw = new BufferedWriter(fw);

            // Append some data to the file
            bw.write("Deposited/"+value+"/Savings/"+formattedDateTime+"\n");

            // Close the writers
            bw.close();
            fw.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JComboBox<String> accountComboBox;
    private javax.swing.JLabel balanceText;
    private javax.swing.JButton confirmButton;
    private javax.swing.JPanel currentBalancePanel;
    private javax.swing.JLabel currentBalanceTitle;
    private javax.swing.JLabel depositLabel;
    private javax.swing.JToggleButton eightyButton;
    private javax.swing.JToggleButton fourtyButton;
    private javax.swing.JToggleButton hundredButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton optionMenuButton;
    private javax.swing.JToggleButton threeHundredButton;
    private javax.swing.JToggleButton twentyButton;
    private javax.swing.JToggleButton twoHundredButton;
    private javax.swing.JLabel withdrawFromText;
    // End of variables declaration//GEN-END:variables
}
