/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;
import java.util.List;
import java.io.*;
/**
 *
 * @author titoosemobor
 */
public class InsertCard extends javax.swing.JFrame {
    private List<User> users;

    private User user;
    private Integer count;

    /**
     * Creates new form InsertCard
     */

    public InsertCard(List<User> users) {
        this.users =  users;

        this.count = 0;

        initComponents();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cardNumberLabel = new javax.swing.JLabel();
        expiryDateLabel = new javax.swing.JLabel();
        piniLabel = new javax.swing.JLabel();
        expiryDate = new javax.swing.JTextField();
        cardNumber = new javax.swing.JTextField();
        pinNumber = new javax.swing.JPasswordField();
        insertButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MetCash");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/titoosemobor/TMU-ComputerSci/JAVA/ATMProject/assets/rsz_4rsz_1rsz_metcash-high-resolution-logo-black-on-transparent-background.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INSERT YOUR CARD");

        cardNumberLabel.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        cardNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cardNumberLabel.setText("CARD NUMBER:");

        expiryDateLabel.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        expiryDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        expiryDateLabel.setText("EXPIRY DATE:");

        piniLabel.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        piniLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        piniLabel.setText("PIN:");

        pinNumber.setToolTipText("");
        pinNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinNumberActionPerformed(evt);
            }
        });

        insertButton.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        insertButton.setText("DONE");
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cardNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(expiryDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(piniLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(expiryDate)
                    .addComponent(cardNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                    .addComponent(pinNumber)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(insertButton)
                .addGap(291, 291, 291))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expiryDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(piniLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pinNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(insertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pinNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinNumberActionPerformed

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        // TODO add your handling code here:
        String cardNum = cardNumber.getText();
        String expDate = expiryDate.getText();
        String pin = new String(pinNumber.getPassword());
        if (checkIfEmpty(cardNum, expDate, pin)) {
            JOptionPane.showMessageDialog(this, "Missing Information");
        }
        else {
            if(count!=3) {
                try {
                    if (getMatchingUser(users, cardNum, expDate, pin) != null) {
                        goToMenu(getMatchingUser(users, cardNum, expDate, pin));
                    } else {
                        JOptionPane.showMessageDialog(this, "Wrong Details");
                        count += 1;
                    }
                } catch (Exception e) {

                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Maximum Attempts Has Been Met");
                this.dispose();
            }
        }
    }//GEN-LAST:event_insertButtonActionPerformed

    public boolean checkIfEmpty(String cardNum, String expDate, String pin) {
        return cardNum.isEmpty() || expDate.isEmpty() || pin.isEmpty();
    }

    public User getMatchingUser(List<User> users,String cardNum,String expDate,String pin) {
        for (User userB : users) {
            if (userB.getCard().getCardNumber().equals(cardNum) &&
                    userB.getCard().getPin().equals(pin) &&
                    userB.getCard().getExpirationDate().equals(expDate)){
                return userB;
            }
        }
        return null;
    }

    public void goToMenu(User user) {
        TransactionMenu newTransMenu = new TransactionMenu(user, users);
        newTransMenu.setVisible(true);
        this.dispose();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cardNumber;
    private javax.swing.JLabel cardNumberLabel;
    private javax.swing.JTextField expiryDate;
    private javax.swing.JLabel expiryDateLabel;
    private javax.swing.JButton insertButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pinNumber;
    private javax.swing.JLabel piniLabel;
    // End of variables declaration//GEN-END:variables
}
