
import java.util.List;

/**;
 *
 * @author Meero
 */
public class TransactionMenu extends javax.swing.JFrame {
    private User user;
    private List<User> users;


    /**
     * Creates new form OptionMenu1
     */
    public TransactionMenu(User user, List<User> users) {
        this.user = user;
        this.users = users;
        initComponents();
        customerName.setText(user.getFirstName() + " " + user.getLastName());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TransactionMenu = new javax.swing.JPanel();
        withDraw = new javax.swing.JButton();
        deposit = new javax.swing.JButton();
        accountInfo = new javax.swing.JButton();
        transferFunds = new javax.swing.JButton();
        payBills = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        customerName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        logOutButton = new javax.swing.JButton();
        changePin = new javax.swing.JButton();
        transactionHistoryButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MetCash");
        setResizable(false);

        TransactionMenu.setForeground(new java.awt.Color(242, 242, 242));
        TransactionMenu.setPreferredSize(new java.awt.Dimension(734, 394));

        withDraw.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        withDraw.setText("Withdraw");
        withDraw.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(153, 153, 153)));
        withDraw.setHideActionText(true);
        withDraw.setMaximumSize(new java.awt.Dimension(154, 31));
        withDraw.setMinimumSize(new java.awt.Dimension(154, 31));
        withDraw.setPreferredSize(new java.awt.Dimension(154, 31));
        withDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withDrawActionPerformed(evt);
            }
        });

        deposit.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        deposit.setText("Deposit");
        deposit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(153, 153, 153)));
        deposit.setMaximumSize(new java.awt.Dimension(154, 31));
        deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositActionPerformed(evt);
            }
        });

        accountInfo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        accountInfo.setText("Account Info");
        accountInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(153, 153, 153)));
        accountInfo.setMaximumSize(new java.awt.Dimension(154, 31));
        accountInfo.setMinimumSize(new java.awt.Dimension(154, 31));
        accountInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountInfoActionPerformed(evt);
            }
        });

        transferFunds.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        transferFunds.setText("Transfer Funds");
        transferFunds.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(153, 153, 153)));
        transferFunds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferFundsActionPerformed(evt);
            }
        });

        payBills.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        payBills.setText("Pay Bills");
        payBills.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(153, 153, 153)));
        payBills.setMaximumSize(new java.awt.Dimension(154, 31));
        payBills.setMinimumSize(new java.awt.Dimension(154, 31));
        payBills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payBillsActionPerformed(evt);
            }
        });

        customerName.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        customerName.setForeground(new java.awt.Color(51, 51, 51));
        customerName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        customerName.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Welcome,");

        logOutButton.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        logOutButton.setText("LOG OUT");
        logOutButton.setToolTipText("");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12)
                        .addComponent(customerName, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(customerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        changePin.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        changePin.setText("Change Pin");
        changePin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(153, 153, 153)));
        changePin.setMaximumSize(new java.awt.Dimension(154, 31));
        changePin.setMinimumSize(new java.awt.Dimension(154, 31));
        changePin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePinActionPerformed(evt);
            }
        });

        transactionHistoryButton.setFont(new java.awt.Font("SansSerif", 0, 17)); // NOI18N
        transactionHistoryButton.setText("Transaction History");
        transactionHistoryButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(153, 153, 153)));
        transactionHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionHistoryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TransactionMenuLayout = new javax.swing.GroupLayout(TransactionMenu);
        TransactionMenu.setLayout(TransactionMenuLayout);
        TransactionMenuLayout.setHorizontalGroup(
            TransactionMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransactionMenuLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(TransactionMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(withDraw, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(payBills, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deposit, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(transactionHistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(TransactionMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accountInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changePin, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transferFunds, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
            .addGroup(TransactionMenuLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 52, Short.MAX_VALUE))
        );
        TransactionMenuLayout.setVerticalGroup(
            TransactionMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransactionMenuLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TransactionMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(withDraw, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TransactionMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changePin, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deposit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(TransactionMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payBills, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transferFunds, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transactionHistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TransactionMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TransactionMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void depositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositActionPerformed
        // TODO add your handling code here:
        Deposit deposit = new Deposit(user,users);
        deposit.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_depositActionPerformed

    private void accountInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountInfoActionPerformed
        // TODO add your handling code here:
        AccountInfo info = new AccountInfo(user, users);
        info.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_accountInfoActionPerformed

    private void transferFundsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferFundsActionPerformed
        // TODO add your handling code here:
        TransferFunds transfer = new TransferFunds(user, users);
        transfer.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_transferFundsActionPerformed

    private void payBillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payBillsActionPerformed
        // TODO add your handling code here:
        PayBill pay = new PayBill(user, users);
        pay.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_payBillsActionPerformed

    private void withDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withDrawActionPerformed
        Withdraw withdraw = new Withdraw(user,users);
        withdraw.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_withDrawActionPerformed
    private void transactionHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionHistoryButtonActionPerformed
        // TODO add your handling code here:
        TransactionHistory transactionHistory = new TransactionHistory(user,users);
        transactionHistory.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_transactionHistoryButtonActionPerformed

    private void changePinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePinActionPerformed
        // TODO add your handling code here:
        ChangePin changepin = new ChangePin(user,users);
        changepin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_changePinActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        // TODO add your handling code here:
        InsertCard login = new InsertCard(users);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logOutButtonActionPerformed


    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TransactionMenu;
    private javax.swing.JButton accountInfo;
    private javax.swing.JButton changePin;
    private javax.swing.JLabel customerName;
    private javax.swing.JButton deposit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton payBills;
    private javax.swing.JButton transactionHistoryButton;
    private javax.swing.JButton transferFunds;
    private javax.swing.JButton withDraw;
    // End of variables declaration//GEN-END:variables
}
